id: PC3A1D7DA
initial_creation_type: input
source_metadata:
  title: Thangtong Gyalpo Series
  language: pt
  description: 'Texts by and about the great siddha and bridge-builder Thangtong Gyalpo
    (thang stong rgyal po, 1361?–1485):'
  volume:
    e52efd2866c744dbba817ba2b73de465:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Longevity
    08fb7c23071a4934a665492d5d4d32cb:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Longevity
    f4cf601892754220bdce0f455cf67a29:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    fbe3097ec32248769d163e963f837add:
      title: Prayer for Dispelling Famine
      parent: Prayers
    9c8e01009143475a981dd1505f1afd35:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Prayers
    8e158ede3ce04e63a7720d7b9b02111b:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    c968f56ab5a646459e3a1b19eb086666:
      title: The Outer, Inner and Secret Refuge Practice of the Mahāsiddha Thangtong
        Gyalpo
      parent: Prayers
    6dc7556ddfd441c1ae24de90717062f8:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
    c43b2cd5bf094f58ba48e01f1a8b7157:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Prayers
    a1068265f97644b3aed304ddfdfd21db:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Sādhanas
created_at: '2022-03-01T01:46:09.361130'
last_modified_at: '2022-03-01T01:46:09.361132'
